# -*- coding: utf-8 -*-
"""tugas 2 contoh Dynamic Programming Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

memo = {}

def fibonacci(n):
    if n in memo:
        return memo[n]

    if n <= 1:
        return n

    memo[n] = fibonacci(n-1) + fibonacci(n-2)
    return memo[n]


print(fibonacci(10))