# -*- coding: utf-8 -*-
"""tugas 2 contoh Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

# membuat class Node
class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None


# fungsi untuk traversal preorder
def preorder(node):
    if node is not None:
        print(node.data)
        preorder(node.left)
        preorder(node.right)


# membuat tree
root = Node("A")
root.left = Node("B")
root.right = Node("C")

root.left.left = Node("D")
root.left.right = Node("E")

# menjalankan traversal
preorder(root)