# -*- coding: utf-8 -*-
"""tugas 2 contoh array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

# membuat list
nilai= [80, 85, 90, 75, 88]

# menampilkan seluruh isi list
print("Semua nilai:", nilai)

# mengambil data pada index ke-2
print("Nilai pada index ke-2:", nilai[2])

# menambah data baru
nilai.append(95)

# menampilkan list setelah ditambah
print("List setelah ditambah:", nilai)

