# -*- coding: utf-8 -*-
"""tugas 2 contoh Simple Recursive Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

def factorial(n):
    if n == 1:
        return 1
    else:
        return n * factorial(n-1)

angka = 5
hasil = factorial(angka)

print("Faktorial =", hasil)