# -*- coding: utf-8 -*-
"""tugas 2 contoh Brute Force Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

password = "123"

for i in range(1000):
    guess = str(i).zfill(3)

    if guess == password:
        print("Password ditemukan:", guess)
        break