# -*- coding: utf-8 -*-
"""tugas 2 contoh Linked list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class LinkedList:
    def __init__(self):
        self.head = None

    def tambah(self, data):
        node_baru = Node(data)

        if self.head is None:
            self.head = node_baru
            return

        temp = self.head
        while temp.next is not None:
            temp = temp.next

        temp.next = node_baru

    def tampil(self):
        temp = self.head
        while temp is not None:
            print(temp.data, end=" -> ")
            temp = temp.next
        print("None")


ll = LinkedList()

ll.tambah(10)
ll.tambah(20)
ll.tambah(30)

ll.tampil()