# -*- coding: utf-8 -*-
"""tugas 2 contoh Stack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

stack = []

stack.append(10)
stack.append(20)
stack.append(30)

print("Stack setelah push:", stack)

keluar = stack.pop()

print("Data yang keluar:", keluar)
print("Stack sekarang:", stack)