# -*- coding: utf-8 -*-
"""tugas 2 contoh Greedy Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

coins = [1000, 500, 200, 100]
jumlah = 2700

hasil = []

for coin in coins:
    while jumlah >= coin:
        jumlah -= coin
        hasil.append(coin)

print("Koin yang digunakan:", hasil)