# -*- coding: utf-8 -*-
"""tugas 2 contoh Queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

from collections import deque

queue = deque()

queue.append(10)
queue.append(20)
queue.append(30)

print("Queue:", queue)

data_keluar = queue.popleft()

print("Data keluar:", data_keluar)
print("Queue sekarang:", queue)