# -*- coding: utf-8 -*-
"""tugas 2 contoh Randomized Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa4eAEXJaXW_UN6pMbfurCeZZ8abpOy3
"""

import random

data = [10, 20, 30, 40, 50]

pilihan = random.choice(data)

print("Angka yang dipilih secara acak:", pilihan)